name: CoordCopy
version: ${version}
author: dmkng
main: io.github.dmkng.CoordCopy.Main
api-version: 1.13
commands:
  coordcopy:
    description: Gives the CoordCopy wand.
    permission: coordcopy.wand
    aliases: [ coordcopywand, coord, coordwand ]
